language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run lint
  - npm run test --passWithNoTests
  - npm run test --coverage
  - npm run build
