language: node_js
node_js:
  - 10.8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
env:
  - CI=true

script:
  - npm run lint
  - npm run test --passWithNoTests
  - npm run test --coverage
    #   ## print all Travis environment variables for debugging
  - $(npm bin)/print-env TRAVIS
  - npm run test:e2e:ci -- --parallel
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true
  - npm run build

