language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
env:
  - CI=true

script:
  - npm run lint
  - npm run test --passWithNoTests
  - npm run test --coverage
  - npm run test:e2e:ci
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true
  - npm run build

