version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8080:8080"
    