version: '3.8'

services:
  frontend:
    container_name: "frontend"
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    ports:
      - "3000:3000"
    