version: '3.8'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
  swagger-api:
    build: .
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8002:8002"
        - "8004:8004"
    volumes:
      - ./fake-api/swagger:/swagger
    command: /swagger/openapi.yaml
    
    