version: "3.3"
services:
  sume-auth:
    image: jboss/keycloak
    ports: 
      - 8080:8080
      - 8443:8443
    environment: 
      - KEYCLOAK_USER=admin 
      - KEYCLOAK_PASSWORD=admin 
      - KEYCLOAK_IMPORT=/realm/sume.json
    volumes:
      - ./realm:/realm
    deploy:
      restart_policy:
        condition: on-failure
